# -*- coding: utf-8 -*-
"""linear_model_mtcars.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AbrPQTE15THlQOq-CX8dyu9kAg-3ffV2
"""



# linear_model_mtcars.py

# Load the mtcars.csv dataset.
# Fit a multiple linear regression model with mpg as the response and all other variables as predictors.
# Output the model summary.

import pandas as pd
import statsmodels.api as sm

# Load dataset
df = pd.read_csv("mtcars.csv")

# Drop the first column
df = df.iloc[:, 1:]

# Define response and predictors
y = df['mpg']
X = df.drop(columns=['mpg'])

# Add constant for intercept
X_const = sm.add_constant(X)

# Fit the model
model = sm.OLS(y, X_const).fit()
print(model.summary())

# Save the summary to a file
with open("model_summary.txt", "w") as f:
    f.write(model.summary().as_text())